<?php

/* this file is part of pipelines */

namespace Ktomk\Pipelines\File;

use Ktomk\Pipelines\File;
use Ktomk\Pipelines\Pipeline;
use Ktomk\Pipelines\Runner\Reference;
use PHPUnit\Framework\TestCase;

/**
 * @covers  \Ktomk\Pipelines\File::searchReference()
 * @covers  \Ktomk\Pipelines\File::searchTypeReference()
 */
class ReferenceSearchTest extends TestCase
{
    /**
     * @var File
     */
    private $file;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->file = File::createFromFile(__DIR__ . '/../../data/bitbucket-pipelines.yml');
    }

    function searchReference($ref = null)
    {
        return $this->file->searchReference(
            Reference::create($ref)
        );
    }

    function testSearching()
    {
        $actual = $this->searchReference('branch:feature/unicorns');
        $this->assertNotNull($actual);

    }

    function testSearchDirect()
    {
        $actual = $this->searchReference('branch:feature/unicorns');
        $this->assertSame('feature/*', $this->getFirstStepName($actual));

        $actual = $this->searchReference('branch:feature/bb-123-fix-links');
        $this->assertSame('feature/bb-123-fix-links', $this->getFirstStepName($actual));
    }

    function testSearchFirstPatternNoHit()
    {
        $actual = $this->searchReference('tag:blue-moon-unicorn-release');
        $this->assertDefault($actual);
    }

    function testSearchNothing()
    {
        $actual = $this->searchReference();
        $this->assertDefault($actual);
    }

    private function getFirstStepName(Pipeline $pipeline)
    {
        $steps = $pipeline->getSteps();
        $name = $steps[0]->getName();

        return $name;
    }

    private function assertDefault(Pipeline $pipeline)
    {
        $default = $this->file->getDefault();
        $this->assertSame($default, $pipeline, 'is default pipeline');
    }
}
